### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-events-api#35]
### Description

Get some typing built into this package.

My 2c is that we should steer away from over-typing the actual events, but we could document at least a couple of "baseline" properties that all events have.

It shouldn't be too hard to describe the actual API of the module though. We should figure out how much JSDoc will do for us since the typescript language service can read JSDoc comments for types now. At this point I don't think there's any need to port to code to `.ts`, but open to hear feedback on this.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by tatethurston** [comment]
Would you be open to a pull request for these?

I've pulled this into a recent typescript project, and would be happy to flesh out my type definitions and share them.

**Comment by aoberoi** [comment]
@tatethurston yeah, for sure!

**Comment by tatethurston** [comment]
Great, I'll make the PR today and then we can discuss iterations once I have something concrete up.

**Comment by shanedewael** [comment]
https://github.com/slackapi/node-slack-sdk/issues/816
