### ISSUE TITLE
Not found in npm

### ISSUE THREAD

**Issue by belal-mazlom** [slackapi/node-slack-events-api#5]
### Description
Seems package not published to npm

### Bug Report

> npm ERR! Darwin 16.3.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "@slack/events-api"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.8
> npm ERR! code E404
> 
> npm ERR! 404 Not found : @slack/events-api
> npm ERR! 404 
> npm ERR! 404  '@slack/events-api' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.

#### Steps to reproduce:
`npm install --save @slack/events-api`

**Comment by aoberoi** [comment]
hi @belal-mazlom, we haven't officially launched this project, so thats why its not on npm just yet.

i think it would be great to get feedback from you and others, so i'll quietly launch a beta version just for you ❤️ .

**Comment by aoberoi** [comment]
fixed in #6 

you should be able to install the package with `npm install --save @slack/events-api@beta`
