### ISSUE TITLE
how to get direct message 

### ISSUE THREAD

**Issue by aakashkag** [slackapi/node-slack-events-api#50]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:
slack-events version:
node version:
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen
node-slack-events-api is working for public channel, i can sniff all public channel message but can't sniff direct message 
#### Actual result:

What actually happened
no response coming for direct message in slackEvents.on('message', (event)=> {}
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
@aakashkag i just wanted you to know that i've seen this and i'll try to reproduce it. thanks for the report!

**Comment by aakashkag** [comment]
i got solution,thanks
