### ISSUE TITLE
Slack Dialog not closing

### ISSUE THREAD

**Issue by Yashrad** [slackapi/node-slack-events-api#53]
### Description

Describe your issue here.
Im using node-slack-interactive-messages to open a dialog and get some data from the user.
After submit the dialog would not close and I get internal_error.
This is what Im trying in the slackMessages.action 

slackMessages.action('create_resource_form_submit', (payload, respond) => {
    let errors = {
        "errors": [
            {
                "name": "resource_type",
                "error": "Some ERROR"
            },
            {
                "name": "location",
                "error": "Some ERROR"
            }
        ]
    };
    respond(errors)
        .then((r)=>{
            console.log("Result is " , r);
        })
        .catch((e)=>{
            console.log("ERROR IN REPOND Is " , e);
        });
});

I also tried sending an empty response with {status : 200} just to close the dialog,
but got invalid_request_data error.

Can anyone please provide any help on this?
 
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

**Comment by aoberoi** [comment]
@Yashrad sorry that this didn't get any feedback for a while. I think you meant to post an issue to [this other repository](https://github.com/slackapi/node-slack-interactive-messages). Closing since this isn't the right place, but happy to help if you're still having that issue. Just open an issue on that repo, please.
