### ISSUE TITLE
Add requestListener usage to README

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-events-api#65]
### Description

We currently describe using the built-in server and the express middleware, but using this adapter as a request listener is also a valid usage.

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
This is described in the documentation (under **Using an express app** at https://slack.dev/node-slack-sdk/events-api) and briefly touched on in the README. Closing this for now, but if it seems like a mistake feel free to reopen the issue in https://github.com/slackapi/node-slack-sdk
