### ISSUE TITLE
I can't verify Production URL for events API

### ISSUE THREAD

**Issue by alexeyvakarchuk** [slackapi/node-slack-events-api#82]
### Description

Hello, everyone! I'm trying to integrate Slack API to my web app using node-slack-events-api (v2.1.1)
But I'm getting error every time when I'm trying to verify my production URL. 

`@slack/events-api` version: 2.1.1
node version: 10.13.0

#### Attachments:
<img width="696" alt="screen shot 2018-12-08 at 8 52 55 pm" src="https://user-images.githubusercontent.com/19474687/49689788-20600b00-fb2f-11e8-91d0-07ca66efa556.png">
<img width="1046" alt="screen shot 2018-12-08 at 9 03 14 pm" src="https://user-images.githubusercontent.com/19474687/49689789-20600b00-fb2f-11e8-8e00-32c021066e77.png">

### Code

``` JavaScript
const path = require('path')
const express = require('express')
const http = require('http')
const { createEventAdapter } = require('@slack/events-api')
const slackEvents = createEventAdapter(process.env.SLACK_SIGNING_SECRET)

const port = process.env.PORT || 3000

const app = express()
const server = http.createServer(app)

app.use('/slack/events', slackEvents.expressMiddleware())

// Attach listeners to events by Slack Event "type". See: https://api.slack.com/events/message.im
slackEvents.on('message', event => {
  console.log(
    `Received a message event: type: ${event.type}, user ${
      event.user
    } in channel ${event.channel} says ${event.text}`
  )
  if (clients.length > 0) {
    clients.map(clientWs => {
      clientWs.send(
        JSON.stringify({
          channel: event.channel,
          author: event.user,
          text: event.text
        })
      )
    })
  }
})

// *** Handle errors ***
slackEvents.on('error', error => {
  console.error(error)
})


server.listen(port, function(err) {
  if (err) {
    return console.error(err)
  }

  console.log('Listening at port: ', port)
})
```

**Comment by aoberoi** [comment]
It seems like you might have already figured this out since you closed the issue, but I’m case you haven’t, all the code looks correct but you’d need to check that your request signing secret is in the `SLACK_SIGNING_SECRET` environment variable.
