### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '..."require-directory":"'

### ISSUE THREAD

**Issue by agustingarcia210988** [slackapi/node-slack-events-api#96]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-events-api/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/events-api` version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by clavin** [comment]
This sounds like it might be an issue with your `package.json` file, notably a missing comma (`,`) before a package named `"require-directory"`. Could you please include the contents of your `package.json` file & the entire error stack trace?

**Comment by shanedewael** [comment]
Hey @agustingarcia210988 👋 did @clavin's suggestion help with your problem?

If not, would you mind reopen your issue in the new repository (https://github.com/slackapi/node-slack-sdk)? We'd be happy to help you more there if you're still running into issues with the package 😄
